### ISSUE TITLE
request： Is it possible to add LSD protocol?

### ISSUE THREAD

**Issue by i990049** [elgatito/plugin.video.elementum#1083]
All-in-one (plugin.video.elementum-0.1.106.zip)
I made a torrent with qbittorrent, I want to let the Android TVbox play the torrent made with qb on the laptop through WIFI, qb supports lsd protocol, can elementum support lsd protocol?
PS: Why can't elementum stream TV series continuously? There are a lot of videos in the torrent, and it quit when elementum finish playing.

**Comment by antonsoroko** [comment]
@i990049 
1. About LSD:

elementum uses libtorrent 1.2 and [it supports LSD](https://github.com/arvidn/libtorrent/blob/RC_1_2/src/lsd.cpp). 

there is setting in elementum about LSD
https://github.com/elgatito/plugin.video.elementum/blob/1af1e5ef109ecb135dc70f7bf8ee86fbeac3f66b/resources/settings.xml#L184
**by default LSD is enabled, but maybe you disabled it?** (i mean - maybe you enabled "Disable LSD" option.)

if it is enabled, then in kodi.log (https://kodi.wiki/view/Log_file#Log_file_location) file you can see
```
warning <general>: [plugin.video.elementum]   DisableLSD: false,
warning <general>: [plugin.video.elementum] INFO  bittorrent   ▶ startServices    Starting LSD...
```

it is enabled in elementum's code here https://github.com/elgatito/elementum/blob/638d5c307b53763e752a698252ecb03de06e085a/bittorrent/service.go#L522.  search for word `enable_lsd` in https://libtorrent.org/reference-Settings.html for details.

**also you can see current status of LSD for particular torrent here (open on web browser):**
`http://IP_OF_ELEMENTUM:65220/info?torrentid=HASH_OF_TORRENT`
(click "status" in elementum's main menu to find out IP, or just find IP in OS on your laptop).
Example:
```
    Flags:
        paused: false 
        auto_managed: true 
        sequential_download: true 
        need_save_resume: true 
        is_seeding: true 
        is_finished: true 
        has_metadata: true 
        has_incoming: false 
        moving_storage: false 
        announcing_to_trackers: true 
        announcing_to_lsd: true <--------------------------
        announcing_to_dht: true 
```

**to really test if LSD works for you**
0. read https://www.bittorrent.org/beps/bep_0014.html to understands which ports and IPs are used
1. check if port 6771 is used by elementum (you can use `netstat` or any other tool for you OS).
on my Linux PC:
```
$ sudo netstat -naptu | grep 6771
udp        0      0 172.17.0.1:6771         0.0.0.0:*                           244366/elementum
```
so correct port is used.
2. use wireshark/tcpdump/etc in your network to see the real traffic (doc above shows format of LSD messages)

when i use tcpdump, i see:
```
$ sudo tcpdump 'port 6771' -A -n -p

16:21:47.412104 IP MY_IP_HERE.6771 > 239.192.152.143.6771: UDP, length 136
E.....@....e...(.....s.s..;.BT-SEARCH * HTTP/1.1
Host: 239.192.152.143:6771
Port: 6895
Infohash: HASH_OF_TORRENT
cookie: 2783e296
```
(239.192.152.143.6771 is IP from documentation - so all looks correct)

**So LSD should work as i can see.** But please do your own tests to verify this.
