### ISSUE TITLE
Guide: how to run Elementum on Xbox

### ISSUE THREAD

**Issue by antonsoroko** [elgatito/plugin.video.elementum#1117]
## Pre-requisites

1. Xbox [can't launch binaries in Kodi](https://github.com/elgatito/plugin.video.elementum/issues/852) and [does not allow to load shared library](https://github.com/elgatito/plugin.video.elementum/issues/115#issuecomment-1415668784) (a hack that elementum uses for new Android) - thus the only way to use Xbox is as a "client" and then run elementum server somewhere else.
2. If you are lucky - then Kodi's web server works for you and then other needed things will work too. **Enable kodi web ui and try to open it** - if it works then you can use Xbox as Elementum client. Disable it after test. See https://forum.kodi.tv/showthread.php?tid=379377 for details if you are unlucky.

## Steps

1. follow steps from https://elementum.surge.sh/getting-started/installation/ and configure Kodi (do not forget this step) and install elementum. you can use `python -m http.server` (or any other http server, or you can use some network share) to share folder with elementum .zip file and then add this shared folder as http source in kodi and then install zip from that source. enable installation from zip  files first in kodi settings.
2. since [Xbox apps has limitations about usage of ports](https://learn.microsoft.com/en-us/previous-versions/windows/uwp/xbox-apps/known-issues#blocked-networking-ports-on-xbox-one), you must set "Local Port" to something like 45221 (instead of standard 65221) in Elementum settings and set "Repository Port" to 45223 (instead of standard 65223) in "ElementumOrg repository" settings.
3. then you need to setup server with Elementum, you can use docker or Linux daemon or Windows service, see https://github.com/antonsoroko/elementum-docker . Some details about client server mode are here https://github.com/elgatito/plugin.video.elementum/issues/2#issuecomment-2710993565 . Do not forget to change the port from **65221** (NOT 65220) to the port value that you used in step 2.
4. then configure elementum as client (on Xbox)  as described in https://github.com/antonsoroko/elementum-docker/blob/main/README.md#pre-requisites
5. that's it. now Xbox acts as elementum client and your server/PC as elementum server. you can use file or memory storage.

(use new repo https://github.com/ElementumOrg/elementum-docker )

**Comment by zicnic** [comment]
I'm trying to get it working on my Xbox Series X and I can't. After several attempts, I've managed to get the server working on my MacOS and Kodi on the same computer. But when it comes to transferring the IP to the Xbox one, they can't connect. I've changed the ports, but the log still shows:
`[0mSetting remote address to 192.168.1.140:65221
[31mERRO  xbmc         ▶ executeJSONRPCEx  [0mdial tcp 192.168.1.140:65221: i/o timeout`

**Comment by antonsoroko** [comment]
@zicnic 
1. You also must change the port on the server side of Elementum, so server (elementum binary) will connect the port that you specified in Xbox's Elementum client. 
2. Also, check that you can open Kodi web ui (you need to enable it first, if course), see step 2 in Pre-requisites, **if not - then you are unlucky like all people in that thread**. (You can disable Kodi web ui after the test.)
3. Also you must enable things described in guide in step 1 in Steps.

**Comment by zicnic** [comment]
> 1. on the server side of Elementum

Yes, I change the .env:
REMOTE_PORT=45221
LOCAL_PORT=45223
 but not work, in the log says the same port 65221..

And example, my xbox ip is 192.168.1.140 and my Mac is 192.168.1.138

REMOTE_IP=192.168.1.140
LOCAL_IP=192.168.1.134

The web service is working fine

**Comment by zicnic** [comment]
I have tried all the possibilities and I have no way, I put my files in case there is something I missed. Sorry is my frist time to do a proyect like this.
docker-compose.yml
`name: 'elementum'
services:
  elementum:
    image: elementum
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ELEMENTUM_VERSION: ${ELEMENTUM_VERSION}
        ELEMENTUM_ARCH: ${ELEMENTUM_ARCH}
    environment:
      - "TZ=${TZ}"
    # Preferred network driver
    #network_mode: "host"
    # If you can't use "host" driver then uncomment this and other LOCAL_PORT lines:
    network_mode: "bridge"
    ports:
      - "${LOCAL_PORT}:${LOCAL_PORT}"
    volumes:
      - ${ELEMENTUM_DOWNLOADS}:/home/ubuntu/elementum_downloads/
      - ${ELEMENTUM_DATA}:/home/ubuntu/elementum_data/
    command:
      - -disableLibrarySync=${DISABLE_LIBRARY_SYNC}
      - -remoteHost=${REMOTE_IP}
      - -remotePort=${REMOTE_PORT}
      - -localHost=${LOCAL_IP}
      - -localPort=${LOCAL_PORT}
      #- -librarySubstitutions="${LIBRARY_SUBSTITUTION1}"
      #- -listenInterfaces=${LIBTORRENT_LISTEN_INTERFACE1}
      #- -listenInterfaces=${LIBTORRENT_LISTEN_INTERFACE2}
      #- -outgoingInterfaces=${LIBTORRENT_OUTGOING_INTERFACE1}
      #- -outgoingInterfaces=${LIBTORRENT_OUTGOING_INTERFACE2}
      #- -localLogin=${ELEMENTUM_LOGIN}
      #- -localPassword=${ELEMENTUM_PASSWORD}
      # For Windows and maybe macOS uncomment:
      - -serverExternalIp=${SERVER_EXTERNAL_IP}
    restart: unless-stopped
`
.env
`TZ=Europe/Madrid
# Directory to download data in case of file storage. Must be set anyway!
ELEMENTUM_DOWNLOADS=./downloads
# Directory for addon's data, like internal elementum's database.
ELEMENTUM_DATA=./data
# If you want setup library - set to false and read README.
DISABLE_LIBRARY_SYNC=true
# IP of Kodi (where elementum client is).
REMOTE_IP=192.168.1.140
# To use following settings uncomment corresponding lines in docker-compose.yml.
# Port of client side, can be set in addon's settings.
REMOTE_PORT=45221
# elementum listens on all local IPs, but you can set specific IP.
LOCAL_IP=192.168.1.134
# Port on which elementum server listens for connection from client.
LOCAL_PORT=65220
# If server is behind NAT (e.g. in container with NAT network) - specify server external IP.
SERVER_EXTERNAL_IP=192.168.1.134
# If you want to use Kodi Library and its sync - then define substitution in format client_library_path|server_library_path.
# /home/ubuntu/elementum_data/elementum_library is default server library path.
#LIBRARY_SUBSTITUTION1=/path/to/library/in/client|/home/ubuntu/elementum_data/elementum_library
#ELEMENTUM_LOGIN=user
#ELEMENTUM_PASSWORD=password
#LIBTORRENT_LISTEN_INTERFACE1=0.0.0.0
#LIBTORRENT_LISTEN_INTERFACE2=0.0.0.0
#LIBTORRENT_OUTGOING_INTERFACE1=0.0.0.0
#LIBTORRENT_OUTGOING_INTERFACE2=0.0.0.0


# Build time environment variables:
ELEMENTUM_VERSION=0.1.111
ELEMENTUM_ARCH=linux_x64
`
The Xbox is configured with ports 45221, 65220 and the server's IP (192.168.1.134)

and elementum log says me:
`INFO  config       ▶ Reload           [0mSetting remote address to 192.168.1.140:45221
[31mERRO  xbmc         ▶ executeJSONRPCEx  [0mdial tcp 192.168.1.140:65221: i/o timeout
[35mCRIT  xbmc         ▶ executeJSONRPCEx  [0mNo available JSON-RPC connection to the add-on
[33mWARN  config       ▶ fetchConfiguration  [0mCan't continue because addon info is empty
[33mWARN  config       ▶ Reload           [0mCould not get configurations: Could not get addon information from Kodi
[31mERRO  main         ▶ main             [0mCould not get addon configuration: Could not get addon information from Kodi`

**Comment by zicnic** [comment]
I've tried all the configurations without success. I don't know what else to try. Sorry, but I'm a bit of a novice at this type of project. Besides testing with OSX, I tried with a Linux virtual machine, but it doesn't work correctly either. I'm posting my files to see if anyone sees a serious error.
The Xbox is configured correctly, I think, with ports currently 45221 and 65220 and the server IP (192.168.1.134)
```
name: 'elementum'
services:
  elementum:
    image: elementum
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ELEMENTUM_VERSION: ${ELEMENTUM_VERSION}
        ELEMENTUM_ARCH: ${ELEMENTUM_ARCH}
    environment:
      - "TZ=${TZ}"
    # Preferred network driver
    #network_mode: "host"
    # If you can't use "host" driver then uncomment this and other LOCAL_PORT lines:
    network_mode: "bridge"
    ports:
      - "${LOCAL_PORT}:${LOCAL_PORT}"
    volumes:
      - ${ELEMENTUM_DOWNLOADS}:/home/ubuntu/elementum_downloads/
      - ${ELEMENTUM_DATA}:/home/ubuntu/elementum_data/
    command:
      - -disableLibrarySync=${DISABLE_LIBRARY_SYNC}
      - -remoteHost=${REMOTE_IP}
      - -remotePort=${REMOTE_PORT}
      - -localHost=${LOCAL_IP}
      - -localPort=${LOCAL_PORT}
      #- -librarySubstitutions="${LIBRARY_SUBSTITUTION1}"
      #- -listenInterfaces=${LIBTORRENT_LISTEN_INTERFACE1}
      #- -listenInterfaces=${LIBTORRENT_LISTEN_INTERFACE2}
      #- -outgoingInterfaces=${LIBTORRENT_OUTGOING_INTERFACE1}
      #- -outgoingInterfaces=${LIBTORRENT_OUTGOING_INTERFACE2}
      #- -localLogin=${ELEMENTUM_LOGIN}
      #- -localPassword=${ELEMENTUM_PASSWORD}
      # For Windows and maybe macOS uncomment:
      - -serverExternalIp=${SERVER_EXTERNAL_IP}
    restart: unless-stopped
```

 ```
DISABLE_LIBRARY_SYNC=true

# IP of Kodi (where elementum client is).
REMOTE_IP=192.168.1.140
# To use following settings uncomment corresponding lines in docker-compose.yml.
# Port of client side, can be set in addon's settings.
REMOTE_PORT=45221
# elementum listens on all local IPs, but you can set specific IP.
LOCAL_IP=192.168.1.134
# Port on which elementum server listens for connection from client.
LOCAL_PORT=65220
# If server is behind NAT (e.g. in container with NAT network) - specify server external IP.
SERVER_EXTERNAL_IP=192.168.1.134
# If you want to use Kodi Library and its sync - then define substitution in format client_library_path|server_library_path.
# /home/ubuntu/elementum_data/elementum_library is default server library path.
#LIBRARY_SUBSTITUTION1=/path/to/library/in/client|/home/ubuntu/elementum_data/elementum_library
#ELEMENTUM_LOGIN=user
#ELEMENTUM_PASSWORD=password
#LIBTORRENT_LISTEN_INTERFACE1=0.0.0.0
#LIBTORRENT_LISTEN_INTERFACE2=0.0.0.0
#LIBTORRENT_OUTGOING_INTERFACE1=0.0.0.0
#LIBTORRENT_OUTGOING_INTERFACE2=0.0.0.0


# Build time environment variables:
ELEMENTUM_VERSION=0.1.111
ELEMENTUM_ARCH=linux_x64


```
Elementum.log
```
INFO  config       ▶ Reload           [0mReloading configuration...
INFO  config       ▶ Reload           [0mSetting remote address to 192.168.1.140:45221
[31mERRO  xbmc         ▶ executeJSONRPCEx  [0mdial tcp 192.168.1.140:65221: i/o timeout
[35mCRIT  xbmc         ▶ executeJSONRPCEx  [0mNo available JSON-RPC connection to the add-on
[33mWARN  config       ▶ fetchConfiguration  [0mCan't continue because addon info is empty
[33mWARN  config       ▶ Reload           [0mCould not get configurations: Could not get addon information from Kodi
[31mERRO  main         ▶ main             [0mCould not get addon configuration: Could not get addon information from Kodi
INFO  main         ▶ main             [0mStarting Elementum daemon
INFO  main         ▶ main             [0mVersion: 0.1.111 LibTorrent: 1.1.14.0 Go: go1.21.1, Threads: 8
[36mDEBU  xbmc         ▶ Init             [0mCould not connect to the host ::1: dial tcp [::1]:9090: connect: connection refused
[36mDEBU  xbmc         ▶ Init             [0mCould not connect to the host 127.0.0.1: dial tcp 127.0.0.1:9090: connect: connection refused
```
